apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-service
  template:
    metadata:
      labels:
        app: expense-service
    spec:
      imagePullSecrets:
        - name: image-pull-expense
      containers:
        - name: expense-service
          image: ghcr.io/inholland-cloud-minor-2526/group7-expense-service/expense-service:24d0a0c5f54dc32c98e4e89e76a27f6f7c18eb75
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
